# -*- coding: utf-8 -*-
"""Ravanya Parawansa_Final_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cE0aAnRwgTsCqrxH1hYmnC2ZRMf-GRap

# Program untuk Mengirim Email
Program ini dapat mengirimkan email kepada beberapa penerima. Email yang dikirim akan memiliki subject. Program tertera dengan bahasa inggris yang memudahkan saya untuk lebih mengertu. Di bawah program, terdapat beberapa langkah untuk mencapai program tersebut yang memperlihatkan pemikiran saya berdasarkan referensi yang saya dapatkan.
#........

##PROGRAM

This is the program. Please refer to the steps down below to know how I got the code, as well as the references.
"""



#Python code to send mail
import smtplib, ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

#receiver file
textfile = open("receiver_list.txt", "w")
for element in receiver_list:
    textfile.write(element + ",")
textfile.close()

#opening
print("Hi there! Let's send an email\n")

#receiver list
receiver_list = []

n = int(input("Please enter the number of email recipients : "))
for i in range(0, n):
	ele = input("enter the recipient email address : ")

	receiver_list.append(ele) # adding the element
	
print("\nThe recipient email has been added.")
print("-----------------------------------\n")

try:
    port = 465  # For SSL
    smtp_server = "smtp.gmail.com"
    sender_email = input('Enter sender address: ')
    receiver_email = receiver_list
    password = input("Type your password and press enter: ")
    message = MIMEMultipart("plain")
    message["Subject"] = input('Enter the email subject: ')
    body_email = MIMEText(input('Enter the contents of the email: '))
    message.attach(body_email)

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
        server.login(sender_email, password)
        server.sendmail(sender_email, receiver_email, message.as_string())

    print("\nYour email has been delivered.")
    print("-----------------------------------\n")

except Exception:
    print("\nMail delivery failed.")
    print("-----------------------------------\n")

"""###1. Starting a Secure SMTP Connection

Using SSL (Secure Sockets Layer) to make sure that the SMTP connection is encrypted, so that your message and login credentials are not easily accessed by others. The email used here (pythonrv2@gmail.com) is a *throwaway account*. The password is **Python789**.

*code reference: https://realpython.com/python-send-email/* 
"""

import smtplib, ssl

port = 465  # For SSL
password = input("Type your password and press enter: ")

# Create a secure SSL context
context = ssl.create_default_context()

with smtplib.SMTP_SSL("smtp.gmail.com", port, context=context) as server:
    server.login("pythonrv2@gmail.com", password)
    # TODO: Send email here

"""###2. Sending Plain-text Email

Using SSL and the same throwaway account.

*code reference: https://realpython.com/python-send-email/*
"""

import smtplib, ssl

port = 465  # For SSL
smtp_server = "smtp.gmail.com"
sender_email = "pythonrv2@gmail.com"  # Enter your address
receiver_email = "vanyaravanya@gmail.com"  # Enter receiver address
password = input("Type your password and press enter: ")
message = """\
Subject: Hi there

This message is sent from Python."""

context = ssl.create_default_context()
with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
    server.login(sender_email, password)
    server.sendmail(sender_email, receiver_email, message)

print("\nYour email has been delivered.")

"""##3. Sending Email to Multiple Receivers

a

*code reference: https://www.etutorialspoint.com/index.php/265-python-send-mail-to-multiple-recipients-using-smtp-server*
"""

#Python code to send mail
import smtplib, ssl

try:
    port = 465  # For SSL
    smtp_server = "smtp.gmail.com"
    sender_email = "pythonrv2@gmail.com"  # Enter your address
    receiver_email = "vanyaravanya@gmail.com"  # Enter receiver address
    password = input("Type your password and press enter: ")
    message = """\
    Subject: Hi there

    This message is sent from Python."""

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
        server.login(sender_email, password)
        server.sendmail(sender_email, receiver_email, message)
    
    print("\nYour email has been delivered.")

except Exception:
    print("Mail delivery failed.")

"""###4. Receiver List

A list of the recipients so that the email will be sent to multiple recipients.

*code reference: https://www.geeksforgeeks.org/python-get-a-list-as-input-from-user/*
"""

# creating an empty list
receiver_list = []

# number of elements as input
n = int(input("Please enter the number of email recipients : "))

# iterating till the range
for i in range(0, n):
	ele = str(input("enter the recipient email address : "))

	receiver_list.append(ele) # adding the element
	
print("\nThe recipient email has been added.")

#list to file
textfile = open("receiver_list.txt", "w")
for element in receiver_list:
    textfile.write(element + "\n")
textfile.close()

print(receiver_list)
receiver_list